version: '3.8'
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: BK
      MYSQL_USER: BK_user
      MYSQL_PASSWORD: BK_password
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    depends_on: [db]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}

volumes:
  mariadb_data:
